jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage from cobertura
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)\coverage.cobertura.xml
...